/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as DashboardGuidelinesRouteImport } from './routes/dashboard/guidelines'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSystemsRouteImport } from './routes/dashboard/systems'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as GuidelinesIndexRouteImport } from './routes/guidelines/index'
import { Route as GuidelinesSlugRouteImport } from './routes/guidelines/$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuidelinesRoute = DashboardGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemsRoute = DashboardSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const GuidelinesIndexRoute = GuidelinesIndexRouteImport.update({
  id: '/guidelines/',
  path: '/guidelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesSlugRoute = GuidelinesSlugRouteImport.update({
  id: '/guidelines/$slug',
  path: '/guidelines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/systems': typeof SystemsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/guidelines': typeof DashboardGuidelinesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/systems': typeof DashboardSystemsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/guidelines/$slug': typeof GuidelinesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guidelines/': typeof GuidelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/systems': typeof SystemsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/guidelines': typeof DashboardGuidelinesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/systems': typeof DashboardSystemsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/guidelines/$slug': typeof GuidelinesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/guidelines': typeof GuidelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/systems': typeof SystemsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/guidelines': typeof DashboardGuidelinesRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/systems': typeof DashboardSystemsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/guidelines/$slug': typeof GuidelinesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guidelines/': typeof GuidelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/systems'
    | '/dashboard/ai'
    | '/dashboard/guidelines'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/systems'
    | '/dashboard/templates'
    | '/guidelines/$slug'
    | '/insights/$slug'
    | '/studio/$projectId'
    | '/templates/$templateId'
    | '/dashboard/'
    | '/guidelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/systems'
    | '/dashboard/ai'
    | '/dashboard/guidelines'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/systems'
    | '/dashboard/templates'
    | '/guidelines/$slug'
    | '/insights/$slug'
    | '/studio/$projectId'
    | '/templates/$templateId'
    | '/dashboard'
    | '/guidelines'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/systems'
    | '/dashboard/ai'
    | '/dashboard/guidelines'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/systems'
    | '/dashboard/templates'
    | '/guidelines/$slug'
    | '/insights/$slug'
    | '/studio/$projectId'
    | '/templates/$templateId'
    | '/dashboard/'
    | '/guidelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SystemsRoute: typeof SystemsRoute
  GuidelinesSlugRoute: typeof GuidelinesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  GuidelinesIndexRoute: typeof GuidelinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guidelines': {
      id: '/dashboard/guidelines'
      path: '/guidelines'
      fullPath: '/dashboard/guidelines'
      preLoaderRoute: typeof DashboardGuidelinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/systems': {
      id: '/dashboard/systems'
      path: '/systems'
      fullPath: '/dashboard/systems'
      preLoaderRoute: typeof DashboardSystemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/guidelines/': {
      id: '/guidelines/'
      path: '/guidelines'
      fullPath: '/guidelines/'
      preLoaderRoute: typeof GuidelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/$slug': {
      id: '/guidelines/$slug'
      path: '/guidelines/$slug'
      fullPath: '/guidelines/$slug'
      preLoaderRoute: typeof GuidelinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardGuidelinesRoute: typeof DashboardGuidelinesRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSystemsRoute: typeof DashboardSystemsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardGuidelinesRoute: DashboardGuidelinesRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSystemsRoute: DashboardSystemsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SystemsRoute: SystemsRoute,
  GuidelinesSlugRoute: GuidelinesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  GuidelinesIndexRoute: GuidelinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
